@host=http://localhost:5179
@hostId=asdasd
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlckFnZ3JlZ2F0ZS5WYWx1ZU9iamVjdHMuVXNlcklkIiwiZ2l2ZW5fbmFtZSI6IkZyYW5jaXNjbyIsImZhbWlseV9uYW1lIjoiTWVuZG96YSIsImp0aSI6ImYxYTZkMzU5LWNjZGEtNGNjNi05MDA5LTQ2YWU4OTUyMmQyYiIsImV4cCI6MTcxNjY1ODg4MCwiaXNzIjoiQnViZXJEaW5uZXJJc3N1ZXIiLCJhdWQiOiJCdWJlckRpbm5lckF1ZGllbmNlIn0.k7b3I18_GzS_nDGW6oaUTWT_wQywpC2hBRlrsCiOzVw
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}