@host=https://localhost:7229

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlckFnZ3JlZ2F0ZS5WYWx1ZU9iamVjdHMuVXNlcklkIiwiZ2l2ZW5fbmFtZSI6IkZyYW5jaXNjbyIsImZhbWlseV9uYW1lIjoiTWVuZG96YSIsImp0aSI6ImJiODhiOWUwLTM0ZmQtNGZlYi04NTQyLTY1YzAxZjY3OWJiNSIsImV4cCI6MTcxNjUyMDA1OSwiaXNzIjoiQnViZXJEaW5uZXJJc3N1ZXIiLCJhdWQiOiJCdWJlckRpbm5lckF1ZGllbmNlIn0.CFp3caUadGymtu-QfMQr3NIqJi_LZGPWBW8FO6XrTzA 