@host=https://localhost:7229

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlckFnZ3JlZ2F0ZS5WYWx1ZU9iamVjdHMuVXNlcklkIiwiZ2l2ZW5fbmFtZSI6IkZyYW5jaXNjbyIsImZhbWlseV9uYW1lIjoiTWVuZG96YSIsImp0aSI6IjBkNWU4OGZmLTQ4ZjYtNGMzOS1iMzU2LThkNTAyNjI2NzQzMSIsImV4cCI6MTcxNjQ5NzU3OCwiaXNzIjoiQnViZXJEaW5uZXJJc3N1ZXIiLCJhdWQiOiJCdWJlckRpbm5lckF1ZGllbmNlIn0.B44Lctdt4IY4n482Kbw2tn0wwu9PDCBiO1120E_quq4